defaults:
  - dataset: cifar
  - encoder: shallow_repeat
  - decoder: shallow
  - optimizer: sgd


name: autoencoder
epoch: 64
seed: 42
reconstruction_loss: mse
sparse_penalty: l1
lamda: 0.01


datamodule:
  num_workers: 6
  batch_size: 128
  split_propotion: 0.2
  pin_memory: True


devices: [0]
in_channels: 32