defaults:
  - dataset: cifar
  - encoder: direct
  - decoder: sew_resnet
  - optimizer: sgd


name: train_network
epoch: 200
seed: 42
reconstruction: mse
sparse_penalty: l1
lamda: 0.5


datamodule:
  num_workers: 6
  batch_size: 128
  split_propotion: 0.2
  pin_memory: True


devices: [0]
in_channels: 8